print('vejamos a área de um retângulo')
base=int(input('Insira o valor da base:'))
altura=int(input('Insira o valor da altura:'))
area=(altura*2)+(base*2)
print('A área é desse retângulo e de:',area)
